# Build image
FROM golang:1.12-alpine as builder

ARG version="1.0.0"
ARG plugins=cors,realip,expires,cache,jwt,git

RUN apk add --no-cache git gcc musl-dev

# build caddy
COPY ./docker/caddy_build.sh /usr/bin/caddy_build.sh
RUN VERSION=${version} PLUGINS=${plugins} /bin/sh /usr/bin/caddy_build.sh

# Dist image
FROM alpine:latest

ENV HTTP_PORT 4200

# install deps
RUN apk update \
        && apk add --no-cache git openssh-client \
        && addgroup -S -g 1001 app \
        && adduser -S -D -h /app -u 1001 -G app app

# copy caddy binary
COPY --from=builder /install/caddy /usr/bin/caddy

# list plugins
RUN /usr/bin/caddy -plugins

COPY config/caddy/Caddyfile /etc/caddy/Caddyfile
COPY docker/caddy_entrypoint.sh /entrypoint.sh

# static files volume
VOLUME ["/www"]
WORKDIR /www

ENTRYPOINT ["/entrypoint.sh"]
