# Build image
FROM golang:1.12-alpine as builder

ARG CADDY_VERSION="0.11.5"

RUN apk add --no-cache git

# clone caddy
RUN git clone https://github.com/mholt/caddy -b "v$CADDY_VERSION" /go/src/github.com/mholt/caddy \
    && cd /go/src/github.com/mholt/caddy \
    && git checkout -b "v$CADDY_VERSION"

# import plugins
COPY config/caddy/plugins.go /go/src/github.com/mholt/caddy/caddyhttp/plugins.go

# clone builder
RUN git clone https://github.com/caddyserver/builds /go/src/github.com/caddyserver/builds

# build caddy
RUN cd /go/src/github.com/mholt/caddy/caddy \
    && go get ./... \
    && go run build.go \
    && mv caddy /go/bin

# Dist image
FROM python:3.6-alpine

ENV HTTP_PORT 4200

# install deps
RUN apk update \
        && apk add --no-cache git openssh-client \
        && pip3 install pipenv \
        && pip3 install gunicorn \
        && addgroup -S -g 1001 app \
        && adduser -S -D -h /app -u 1001 -G app app

# copy caddy binary
COPY --from=builder /go/bin/caddy /usr/bin/caddy

# list plugins
RUN /usr/bin/caddy -plugins

COPY config/caddy/Caddyfile /etc/caddy/Caddyfile
COPY scripts /pyadmin
COPY schema.txt /schema.txt
COPY .env /.env
COPY docker/caddy_entrypoint.sh /entrypoint.sh

WORKDIR /pyadmin

# install flask and other python deps
RUN pipenv install --deploy --system

# static files volume
VOLUME ["/www"]
WORKDIR /www

ENTRYPOINT ["/entrypoint.sh"]
