FROM golang:1.13-alpine

ENV GOPATH /go
ENV DOCKERIZE_VERSION v0.6.1

RUN apk add --no-cache openssl

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN wget https://github.com/cosmtrek/air/raw/master/bin/linux/air && chmod +x air && mv air /usr/local/bin

WORKDIR /pandora

ENTRYPOINT ["dockerize", "--wait", "tcp://dgraph:9080", "--wait", "tcp://minio:9000", "--wait", "tcp://nats:4222", "/usr/local/bin/air"]
